### ISSUE TITLE
[FEA] source activate rapids on docker entrypoint

### ISSUE THREAD

**Issue by miguelangel** [rapidsai/build#19]
**Is your feature request related to a problem? Please describe.**
Hi,

I have noticed that RAPIDS container automatically activates rapids environment only running _docker run_ as _root_.

That is due to the fact that the _source activate rapids_ command is in a root startup script.

Might I suggest a different approach (invoking a script in the entry point)? That way, it would work with any user passed to docker with the --user command.

https://stackoverflow.com/a/44079215/3687310

Thanks!
Miguel

**Comment by datametrician** [comment]
@kkraus14 can we triage this and get a release target?

**Comment by kkraus14** [comment]
@rlratzel Is this something you could tackle?

**Comment by rlratzel** [comment]
> @rlratzel Is this something you could tackle?

Yes, I'll take a look.

**Comment by rlratzel** [comment]
I have something that works in my test environment. I'll close this when the next set of nightly containers has this.

**Comment by miguelangel** [comment]
Awesome! Thank you @rlratzel!

**Comment by rlratzel** [comment]
This should be working in the latest nightlies:

https://cloud.docker.com/u/rapidsai/repository/docker/rapidsai/rapidsai-nightly
