### ISSUE TITLE
[FEA] Remove cuda labels from conda channels

### ISSUE THREAD

**Issue by rlratzel** [rapidsai/build#24]
**Is your feature request related to a problem? Please describe.**
This change keeps consistency between the Dockerfiles generated here and the conda installs done in gpuCI.

**Describe the solution you'd like**
Channel names consistent with those in the `.condarc` shown in this PR: https://github.com/rapidsai/gpuci-build-environment/pull/25

**Additional context**
https://github.com/rapidsai/gpuci-build-environment/pull/25

**Comment by mluukkainen** [comment]
WIP patch here: https://github.com/rapidsai/build/pull/27

**Comment by mike-wendt** [comment]
Given that we can build and use the containers with the changes in `branch-0.9` I think we should put this issue and #27 on the backlog and revisit after the release

**Comment by mluukkainen** [comment]
I moved this against branch-0.10 and images build. From my POV it could go in if the PR is still needed:

https://github.com/rapidsai/build/pull/27/files
