### ISSUE TITLE
[FEA] Add cuSpatial repo/package to all Docker images

### ISSUE THREAD

**Issue by rlratzel** [rapidsai/build#35]
This repo and corresponding conda package needs to be added to the appropriate Docker images:
https://github.com/rapidsai/cuspatial
https://anaconda.org/rapidsai-nightly/cuspatial

`devel` images will have the new repo added alongside the other repos in `/rapids` and will have it built and installed from sources (using standard `build.sh`)
* NOTE: the current `cuspatial` build process requires that it be built *after* `cudf`, since it dependes on `cudf` headers and libs.

`base` will need `cuspatial` added to the `conda install` line (and therefore `runtime` will automatically have it included)

**Comment by mluukkainen** [comment]
I have patch ready but not fully tested. Base images both build and ubuntu-devel also builds. Verifying centos7-devel image now. Patch is here:

https://github.com/rapidsai/build/pull/36/files

**Comment by rlratzel** [comment]
https://github.com/rapidsai/build/pull/36 has been merged.
