### ISSUE TITLE
Feature request / regression: py3.7 in production docker releases to support BlazingSQL

### ISSUE THREAD

**Issue by lmeyerov** [rapidsai/build#42]
**Issue:**

Trying BlazingSQL via a container is difficult, and then going to it in production is difficult, because RAPIDS docker no longer has py3.7 and Blazing requires py3.7. This change happened about 2mo ago. 

For new users, navigating dependencies is non-trivial, and for heavy users, the sizes involved make the process slow.

**Workaround**:

We created an interim container:

```
FROM gpuci/miniconda-cuda-rapidsenv:10.0-devel-ubuntu18.04-py3.7

RUN source activate rapids \
 && conda install -c rapidsai -c nvidia -c conda-forge -c defaults rapids=0.10 python=3.7
```

=> https://hub.docker.com/r/graphistry/graphistry-nvidia

cc @felipeblazing @mike-wendt

**Comment by mike-wendt** [comment]
> FWIW, just changed from gpuci/miniconda-cuda-rapidsenv (2.77GB including w/ conda install rapids)

What tag of this are you using? What you're describing isn't much different from what we do now.

**Comment by lmeyerov** [comment]
`nvidia/cuda:10-runtime-ubuntu18.04`

We then do `g++, boost, ...` -> `miniconda` -> `python3.7`. I _think_ we can eliminate some of the buildessentials / g++ stuff, but am unsure about numba, and for some of our downstream python/node libs, if we can move their compilation to buildtime. So keeping for now.

**Comment by rlratzel** [comment]
Releases now include both `py3.6` and `py3.7` versions of `base` and `runtime` Docker images:
https://hub.docker.com/repository/docker/rapidsai/rapidsai
