### ISSUE TITLE
[FEA] Add jupyterlab-nvdashboard to docker runtime containers

### ISSUE THREAD

**Issue by miguelangel** [rapidsai/build#45]
**Is your feature request related to a problem? Please describe.**
Hi,

I am not sure if this is the right place to add this Feature request.

I think it would be great to add the `jupyterlab-nvdashboard` extension to RAPIDS runtime containers.

More info here:
https://medium.com/rapids-ai/gpu-dashboards-in-jupyter-lab-757b17aae1d5

**Describe the solution you'd like**
To have jupyterlab-nvdashboard preinstalled on RAPIDS runtime containers.

**Describe alternatives you've considered**
Install it myself.

**Comment by jacobtomlinson** [comment]
It is already there but currently broken. See #43

**Comment by miguelangel** [comment]
Awesome! Closing this issue because of duplicated with #43 .
